# Generated by Django 4.2 on 2025-02-22 11:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_broker_order_stack_contract_order_stack_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broker_order_stack',
            options={'verbose_name': 'Broker Order Stack', 'verbose_name_plural': 'Broker Order Stacks'},
        ),
        migrations.AlterModelOptions(
            name='contract_order_stack',
            options={'verbose_name': 'Contract Order Stack', 'verbose_name_plural': 'Contract Order Stacks'},
        ),
        migrations.AlterModelOptions(
            name='instrument_order_stack',
            options={'verbose_name': 'Instrument Order Stack', 'verbose_name_plural': 'Instrument Order Stacks'},
        ),
        migrations.AddField(
            model_name='broker_order_stack',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='broker_order_stack',
            name='ident',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contract_order_stack',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='contract_order_stack',
            name='ident',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='instrument_order_stack',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='instrument_order_stack',
            name='ident',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='broker_order_stack',
            name='data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='contract_order_stack',
            name='data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='instrument_order_stack',
            name='data',
            field=models.JSONField(),
        ),
        migrations.AlterUniqueTogether(
            name='broker_order_stack',
            unique_together={('ident',)},
        ),
        migrations.AlterUniqueTogether(
            name='contract_order_stack',
            unique_together={('ident',)},
        ),
        migrations.AlterUniqueTogether(
            name='instrument_order_stack',
            unique_together={('ident',)},
        ),
    ]
