# Generated by Django 4.2.9 on 2024-02-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metrics', models.JSONField()),
                ('additional_info', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='TradingRuleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('function', models.CharField(max_length=100)),
                ('data', models.JSONField()),
                ('other_args', models.JSONField()),
            ],
        ),
    ]
