# Generated by Django 4.2.9 on 2024-02-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0002_tradingconfiguration_tradingruleconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestresult',
            name='ann_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='ann_std',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='avg_drawdown',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='avg_gain',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='avg_loss',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='avg_return_to_drawdown',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='calmar',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='gaintolossratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='hitrate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='median',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='p_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='profitfactor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='sharpe',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='skew',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='sortino',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='std',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='t_stat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='time_in_drawdown',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backtestresult',
            name='metrics',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
