# Generated by Django 4.2.9 on 2024-01-31 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0003_tradingrule'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TradingRule',
            new_name='TradingRuleModel',
        ),
    ]
