# Generated by Django 4.2 on 2024-02-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0003_backtestresult_ann_mean_backtestresult_ann_std_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestResult2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('min', models.FloatField(blank=True, null=True)),
                ('max', models.FloatField(blank=True, null=True)),
                ('median', models.FloatField(blank=True, null=True)),
                ('mean', models.FloatField(blank=True, null=True)),
                ('std', models.FloatField(blank=True, null=True)),
                ('skew', models.FloatField(blank=True, null=True)),
                ('ann_mean', models.FloatField(blank=True, null=True)),
                ('ann_std', models.FloatField(blank=True, null=True)),
                ('sharpe', models.FloatField(blank=True, null=True)),
                ('sortino', models.FloatField(blank=True, null=True)),
                ('avg_drawdown', models.FloatField(blank=True, null=True)),
                ('time_in_drawdown', models.FloatField(blank=True, null=True)),
                ('calmar', models.FloatField(blank=True, null=True)),
                ('avg_return_to_drawdown', models.FloatField(blank=True, null=True)),
                ('avg_loss', models.FloatField(blank=True, null=True)),
                ('avg_gain', models.FloatField(blank=True, null=True)),
                ('gaintolossratio', models.FloatField(blank=True, null=True)),
                ('profitfactor', models.FloatField(blank=True, null=True)),
                ('hitrate', models.FloatField(blank=True, null=True)),
                ('t_stat', models.FloatField(blank=True, null=True)),
                ('p_value', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
