# Generated by Django 4.2 on 2024-02-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0004_backtestresult2'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestresult2',
            name='instruments',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
