# Generated by Django 4.2.9 on 2024-01-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(max_length=50)),
                ('instrument', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=50)),
                ('contract', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
