# Generated by Django 4.2.9 on 2024-01-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='instrument',
            field=models.CharField(max_length=50),
        ),
    ]
