# Generated by Django 4.2.9 on 2024-01-16 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='price',
            new_name='close_price',
        ),
        migrations.AddField(
            model_name='quote',
            name='high_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='low_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='open_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='volume',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
