# Generated by Django 4.2.9 on 2024-01-23 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_alter_quote_instrument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplepricedata',
            name='carry_contract',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='multiplepricedata',
            name='forward_contract',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
