# Generated by Django 4.2.9 on 2024-01-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_pricedata_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricedata',
            name='instrument',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
