# Generated by Django 4.2 on 2024-02-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_lastdownloaddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastdownloaddate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
