# Generated by Django 4.2.9 on 2024-01-17 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_rename_price_quote_close_price_quote_high_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
