# Generated by Django 4.2.9 on 2024-01-22 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_pricedata_instrument'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjustedPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('price', models.FloatField()),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.quote')),
            ],
        ),
    ]
