# Generated by Django 4.2 on 2024-02-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_lastdownloaddate_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArcticDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.CharField(max_length=255, unique=True)),
                ('data', models.JSONField()),
            ],
        ),
    ]
