# Generated by Django 4.2.9 on 2024-01-24 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_alter_multiplepricedata_carry_contract_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpreadCosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spreadcost', models.FloatField()),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.instrument')),
            ],
        ),
    ]
