# Generated by Django 4.2.9 on 2024-01-17 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_alter_quote_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='secid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
