# Generated by Django 4.2.9 on 2024-01-25 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_spreadcosts'),
    ]

    operations = [
        migrations.AddField(
            model_name='fxpricedata',
            name='currency',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
