# Generated by Django 4.2.9 on 2024-01-17 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_quote_secid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='close_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='quote',
            name='high_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='quote',
            name='low_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='quote',
            name='open_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='quote',
            name='volume',
            field=models.FloatField(default=0),
        ),
    ]
