# Generated by Django 4.2.9 on 2024-01-22 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_adjustedprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adjustedprice',
            name='quote',
        ),
        migrations.AddField(
            model_name='adjustedprice',
            name='price_date',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quotes.pricedata'),
            preserve_default=False,
        ),
    ]
