# Generated by Django 4.2.9 on 2024-01-27 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_fxpricedata_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='RollParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(max_length=50)),
                ('hold_rollcycle', models.CharField(max_length=50)),
                ('priced_rollcycle', models.CharField(max_length=50)),
                ('roll_offset_day', models.IntegerField(default=0)),
                ('carry_offset', models.IntegerField(default=-1)),
                ('approx_expiry_offset', models.IntegerField(default=0)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.instrument')),
            ],
        ),
    ]
