# Generated by Django 4.2.9 on 2024-01-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_alter_quote_close_price_alter_quote_high_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='sectype',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
