# Generated by Django 4.2.9 on 2024-01-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0007_quote_sectype'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('carry', models.FloatField()),
                ('carry_contract', models.CharField(max_length=10)),
                ('price', models.FloatField()),
                ('price_contract', models.CharField(max_length=10)),
                ('forward', models.FloatField()),
                ('forward_contract', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RollCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_contract', models.CharField(max_length=50)),
                ('next_contract', models.CharField(max_length=50)),
                ('start_of_roll_period', models.DateTimeField()),
                ('end_of_roll_period', models.DateTimeField()),
            ],
        ),
    ]
