# Generated by Django 4.2.9 on 2024-01-18 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0008_pricedata_rollcalendar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RollCalendar',
        ),
    ]
