# Generated by Django 4.2.9 on 2024-01-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0009_delete_rollcalendar'),
    ]

    operations = [
        migrations.CreateModel(
            name='RollCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(max_length=50)),
                ('current_contract', models.CharField(max_length=50)),
                ('next_contract', models.CharField(max_length=50)),
                ('start_of_roll_period', models.DateTimeField()),
                ('end_of_roll_period', models.DateTimeField()),
            ],
        ),
    ]
